// <auto-generated />
using System;
using Kuhlschrank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kuhlschrank.Migrations
{
    [DbContext(typeof(KuhlschrankContext))]
    [Migration("20181127120627_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kuhlschrank.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Code");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Place");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Kuhlschrank.Models.ClientFridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<int?>("FridgeId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FridgeId");

                    b.ToTable("ClientFridge");
                });

            modelBuilder.Entity("Kuhlschrank.Models.Fridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activated");

                    b.Property<string>("SerialNumber");

                    b.Property<double>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("Fridge");
                });

            modelBuilder.Entity("Kuhlschrank.Models.ClientFridge", b =>
                {
                    b.HasOne("Kuhlschrank.Models.Client", "Client")
                        .WithMany("Fridges")
                        .HasForeignKey("ClientId");

                    b.HasOne("Kuhlschrank.Models.Fridge", "Fridge")
                        .WithMany("Clients")
                        .HasForeignKey("FridgeId");
                });
#pragma warning restore 612, 618
        }
    }
}
